import type { SegmentBlueprint } from './types';

export const SEGMENT_BLUEPRINTS: SegmentBlueprint[] = [
  {
    id: 'rgp',
    name: 'RGP Simulation',
    assets: [
      {
        assetId: 'sphere',
        instanceId: 'sphere-primary',
        config: {
          speedPerTick: 1,
          direction: 1,
          plane: 'YG',
          shellSize: 32,
          baseColor: 'azure',
          visible: true,
          shadingIntensity: 0.4,
          opacity: 1,
        },
      },
      {
        assetId: 'sphere',
        instanceId: 'sphere-secondary',
        config: {
          speedPerTick: 0.75,
          direction: -1,
          plane: 'GB',
          shellSize: 24,
          baseColor: 'crimson',
          visible: true,
          shadingIntensity: 0.55,
          opacity: 0.85,
          initialRotationY: Math.PI / 4,
        },
      },
    ],
  },
  {
    id: 'rgp-formation',
    name: 'RGP Formation',
    assets: [
      {
        assetId: 'rgpXY',
        instanceId: 'rgp-xy',
        config: {
          size: 24,
          visible: true,
        },
      },
    ],
  },
  {
    id: 'RGP_Pray',
    name: 'RGP_Pray',
    assets: [
      {
        assetId: 'ring-twirl',
        instanceId: 'K1 Ring Twirl',
        config: {
          ringPlane: 'GB',
          ringShellSize: 24,
          ringColor: 'white',
          ringShadingIntensity: 0.4,
          ringOpacity: 0.9,
          ringBeltHalfAngle: 0.18,
          pulseSpeed: 0.75,
          twirlAxis: 'y',
          twirlRadius: 24,
          twirlColor: 'white',
          twirlBackColor: 'white',
          twirlOpacity: 0.85,
          twirlSize: 0.3,
          twirlWidth: 0.3,
          twirlLobeRotationDeg: 20,
          speedPerTick: 1,
          direction: 1,
          visible: true,
          invertPulse: true,
          twirlInvertPulse: true,
        },
      },
      {
        assetId: 'ring-twirl',
        instanceId: 'P2 Ring Twirl',
        config: {
          ringPlane: 'YG',
          ringShellSize: 24,
          ringColor: 'crimson',
          ringShadingIntensity: 0.55,
          ringOpacity: 0.9,
          ringBeltHalfAngle: 0.22,
          pulseSpeed: 0.75,
          twirlAxis: 'z',
          twirlRadius: 24,
          twirlColor: 'crimson',
          twirlBackColor: 'red',
          twirlOpacity: 0.9,
          twirlSize: 0.3,
          twirlWidth: 0.3,
          twirlLobeRotationDeg: 20,
          speedPerTick: 1,
          direction: 1,
          visible: true,
          invertPulse: false,
          twirlInvertPulse: false,
        },
      },
    ],
  },
  {
    id: 'RGP_3',
    name: 'RGP_3',
    assets: [
      {
        assetId: 'rgpXY',
        instanceId: 'rgp-xy',
        config: {
          size: 24,
          visible: true,
        },
      },
      {
        assetId: 'k1p2',
        instanceId: 'K1 Twirl',
        config: {
          axis: 'y',
          radius: 24,
          color: 'white',
          backColor: 'white',
          opacity: 0.85,
          width: 0.3,
          lobeRotationDeg: 20,
          visible: true,
          invertPulse: false,
        },
      },
      {
        assetId: 'k1p2',
        instanceId: 'P2 Twirl',
        config: {
          axis: 'z',
          radius: 24,
          color: 'crimson',
          backColor: 'red',
          opacity: 0.9,
          shadingIntensity: 0.65,
          width: 0.3,
          lobeRotationDeg: 20,
          visible: true,
          invertPulse: true,
        },
      },
    ],
  },
  {
    id: 'RGP_PW',
    name: 'RGP_PW',
    assets: [
      {
        assetId: 'twirling-axis',
        instanceId: 'RGP_PW_AXIS',
        config: {
          visible: false,
          emitGhost: false,
        },
      },
      {
        assetId: 'sphere',
        instanceId: 'rgp-pw-sphere',
        config: {
          plane: 'GB',
          shellSize: 8,
          baseColor: 'azure',
          visible: true,
          shadingIntensity: 0.1,
          opacity: 0.25,
        },
      },
      {
        assetId: 'ring-twirl',
        instanceId: 'K1 PW',
        config: {
          ringPlane: 'GB',
          ringShellSize: 26,
          ringColor: 'white',
          ringShadingIntensity: 0.4,
          ringOpacity: 0.92,
          ringBeltHalfAngle: 0.2,
          pulseSpeed: 0.8,
          twirlAxis: 'y',
          twirlRadius: 26,
          twirlColor: 'white',
          twirlBackColor: 'azure',
          twirlOpacity: 0.9,
          twirlSize: 0.32,
          twirlWidth: 0.32,
          twirlLobeRotationDeg: 18,
          speedPerTick: 1,
          direction: 1,
          visible: true,
          invertPulse: true,
          twirlInvertPulse: true,
        },
      },
      {
        assetId: 'ring-twirl',
        instanceId: 'P2 PW',
        config: {
          ringPlane: 'YG',
          ringShellSize: 28,
          ringColor: 'crimson',
          ringShadingIntensity: 0.55,
          ringOpacity: 0.95,
          ringBeltHalfAngle: 0.24,
          pulseSpeed: 0.8,
          twirlAxis: 'z',
          twirlRadius: 28,
          twirlColor: 'crimson',
          twirlBackColor: 'red',
          twirlOpacity: 0.9,
          twirlSize: 0.34,
          twirlWidth: 0.34,
          twirlLobeRotationDeg: 22,
          speedPerTick: 1,
          direction: 1,
          visible: true,
          invertPulse: false,
          twirlInvertPulse: false,
        },
      },
    ],
    ghosts: [
      {
        id: 'ghost-core',
        position: [0, 0, 0],
        color: [0.2, 0.5, 0.95],
        radius: 0.2,
        opacity: 0.4,
      },
      {
        id: 'ghost-k1',
        position: [0, 0.4, 0],
        color: [0.85, 0.9, 1],
        radius: 0.08,
        opacity: 0.3,
      },
    ],
  },
];
